version: '3.8'

networks:
  default:
    name: blockscout

services:
  redis-db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: redis-db
    command: redis-server
    volumes:
      - redis-data:/data

  blockscout:
    depends_on:
      - smart-contract-verifier
      - redis-db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 5.1.5
    restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    #command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\""
    command: bash -c "bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      - DATABASE_URL=postgresql://postgres:@host.docker.internal:25432/blockscout
      - ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:28545
      - SUBNETWORK=Karura Chain
      - COIN=KAR
      - COIN_NAME=KAR
      - CHAIN_ID=686
      - JSON_RPC=https://eth-rpc-karura.aca-api.network
       - SECRET_KEY_BASE=7DnBT0I+fardSnB5h7Mf9UsvCIxLDaSLrjcnLnFIc8en+uoPPqwmb1oba2Fln/yu
      - SUPPORTED_CHAINS=[
            {"title":"Acala mainnet","url":"https://blockscout.acala.network/","test_net?":false},
            {"title":"Acala mainnet - subscan","url":"https://acala.subscan.io/","test_net?":false},
            {"title":"Karura mainnet","url":"https://blockscout.karura.network/","test_net?":false},
            {"title":"Karura mainnet - subscan","url":"https://karura.subscan.io/","test_net?":false},
            {"title":"Mandala testnet","url":"https://blockscout.mandala.aca-staging.network/","test_net?":true},
            {"title":"Mandala testnet - subscan","url":"https://acala-testnet.subscan.io/","test_net?":true}
          ]
      - INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
      - INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
      - ACCOUNT_POOL_SIZE=20
      - ACCOUNT_REDIS_URL=redis://redis-db:6379
      - INDEXER_TOKEN_BALANCES_BATCH_SIZE=10
      - INDEXER_COIN_BALANCES_BATCH_SIZE=10
      - INDEXER_RECEIPTS_BATCH_SIZE=10
      - BLOCKSCOUT_VERSION=v5.1.5-beta
      - RELEASE_LINK=https://github.com/blockscout/blockscout/releases/tag/v5.1.5-beta
    ports:
      - 4000:4000
    healthcheck:
      test: ["CMD-SHELL", "curl -sS 'http://localhost:4000/api/v1/health' | jq -e .healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 10s
  autoheal:
    restart: always
    image: willfarrell/autoheal
    container_name: autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - logs:/app/logs/

  smart-contract-verifier:
    extends:
      file: ./services/docker-compose-smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

volumes:
  ? redis-data
  ? logs
