version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    # build:
    #   context: ..
    #   dockerfile: ./docker/Dockerfile
    #   args:
    #     CACHE_EXCHANGE_RATES_PERIOD: ""
    #     API_V1_READ_METHODS_DISABLED: "false"
    #     DISABLE_WEBAPP: "false"
    #     API_V1_WRITE_METHODS_DISABLED: "false"
    #     CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
    #     CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
    #     ADMIN_PANEL_ENABLED: ""
    #     RELEASE_VERSION: 6.1.0
    links:
      - db:database
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      SUBNETWORK: Acala Chain
      COIN: ACA
      COIN_NAME: ACA
      ACCOUNT_POOL_SIZE: 10
      # INDEXER_TOKEN_BALANCES_BATCH_SIZE: 2
      # INDEXER_COIN_BALANCES_BATCH_SIZE: 2

      INDEXER_EMPTY_BLOCKS_SANITIZER_BATCH_SIZE: 2
      INDEXER_CATCHUP_BLOCKS_BATCH_SIZE: 2
      INDEXER_CATCHUP_BLOCKS_CONCURRENCY: 1
      INDEXER_CATCHUP_BLOCK_INTERVAL: 30s
      INDEXER_BLOCK_REWARD_BATCH_SIZE: 2
      INDEXER_BLOCK_REWARD_CONCURRENCY: 1
      INDEXER_RECEIPTS_BATCH_SIZE: 2
      INDEXER_RECEIPTS_CONCURRENCY: 1
      INDEXER_COIN_BALANCES_BATCH_SIZE: 2
      INDEXER_COIN_BALANCES_CONCURRENCY: 1
      INDEXER_TOKEN_CONCURRENCY: 1
      INDEXER_TOKEN_BALANCES_BATCH_SIZE: 2
      INDEXER_TOKEN_BALANCES_CONCURRENCY: 1
      INDEXER_CATCHUP_MISSING_RANGES_BATCH_SIZE: 2   # 100000
      MIN_MISSING_BLOCK_NUMBER_BATCH_SIZE: 2         # 100000
      DENORMALIZATION_MIGRATION_BATCH_SIZE: 2          # 500
      DENORMALIZATION_MIGRATION_CONCURRENCY: 1          # 10
      RE_CAPTCHA_CLIENT_KEY: 
      RE_CAPTCHA_SECRET_KEY: 

      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
      INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: true
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
      CHAIN_ID: 787

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider

  # frontend:
  #   depends_on:
  #     - backend
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   extends:
  #     file: ./services/frontend.yml
  #     service: frontend

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      - backend
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
    extends:
      file: ./services/stats.yml
      service: stats

  proxy:
    depends_on:
      - backend
      # - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
