version: '3.8'

networks:
  default:
    name: blockscout

services:
  redis-db:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    container_name: redis_db
    command: redis-server
    volumes:
      - redis-data:/data

  blockscout:
    depends_on:
      - smart-contract-verifier
      - redis-db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        DISABLE_READ_API: "false"
        API_PATH: "/"
        NETWORK_PATH: "/"
        DISABLE_WEBAPP: "false"
        DISABLE_WRITE_API: "false"
        CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        SOCKET_ROOT: "/"
        WOBSERVER_ENABLED: "false"
        ADMIN_PANEL_ENABLED: ""
    restart: always
    container_name: 'blockscout'
    #command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\""
    command: bash -c "bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      - DATABASE_URL=postgresql://postgres:@host.docker.internal:25432/blockscout
      - ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:28545
      - SUBNETWORK=Acala Chain
      - COIN=ACA
      - COIN_NAME=ACA
      - CHAIN_ID=597
      - JSON_RPC=https://eth-rpc-acala-testnet.aca-staging.network/
      - SECRET_KEY_BASE=x4+G3f7F6sxi++wGvdJ5xTGRDOJ7Jo/gsF/PSbDVTuPY+XERE++EX0hKXmyHAyeh
      - SUPPORTED_CHAINS=[
            {"title":"Acala mainnet","url":"https://blockscout.acala.network/","test_net?":false},
            {"title":"Acala mainnet - subscan","url":"https://acala.subscan.io/","test_net?":false},
            {"title":"Karura mainnet","url":"https://blockscout.karura.network/","test_net?":false},
            {"title":"Karura mainnet - subscan","url":"https://karura.subscan.io/","test_net?":false},
            {"title":"Acala testnet","url":"https://blockscout.acala-dev.aca-dev.network/","test_net?":true},
            {"title":"Karura testnet","url":"https://blockscout.karura-testnet.aca-staging.network/","test_net?":true},
            {"title":"Mandala testnet","url":"https://blockscout.mandala.aca-staging.network/","test_net?":true},
            {"title":"Mandala testnet - subscan","url":"https://acala-testnet.subscan.io/","test_net?":true}
          ]
      - INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
      - INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
      - ACCOUNT_POOL_SIZE=20
      - BLOCKSCOUT_VERSION=v4.1.8-beta
      - RELEASE_LINK=https://github.com/blockscout/blockscout/releases/tag/v4.1.8-beta
    ports:
      - 4000:4000

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    environment:
      - SMART_CONTRACT_VERIFIER_DOCKER_TAG=v0.6.0
    restart: always
    container_name: 'smart-contract-verifier'
    env_file:
      -  ./envs/common-smart-contract-verifier.env
    ports:
      - 8043:8043

volumes:
  ? redis-data
